# Loads default set of integrations except for the streaming that requires go2rtc. Do not remove.
frontend:
config:
person:
sun:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

logger:
  default: info
  logs:
    custom_components.schluter: debug
    # write debug log for the aioschluter library
    aioschluter: debug
